### ISSUE TITLE
Catalog generator based on the new data portfolio

### ISSUE THREAD

**Issue by silviacaprioli** [DestinE-Climate-DT/AQUA#1265]
### Discussion

I took a deeper look into the new [data-portfolio repo](https://earth.bsc.es/gitlab/digital-twins/de_340-2/data-portfolio) by Iker. I started adapting our jinja catalog generator but I have some doubts about the best strategy to follow. I was thinking of building a python script that:

- does a `git clone` of the two repositories [data-portfolio](https://earth.bsc.es/gitlab/digital-twins/de_340-2/data-portfolio) and [Climate-DT-catalog](https://github.com/DestinE-Climate-DT/Climate-DT-catalog), so we can directly exploit the files of the data-portfolio and we can update the catalog once the new catalog entry has been generated.
- we build in advance three jinja templates (like [this one](https://github.com/DestinE-Climate-DT/AQUA/blob/main/cli/fdb-catalogue-generator/ifs-nemo-default.j2)), one for each model listed [here](https://earth.bsc.es/gitlab/digital-twins/de_340-2/data-portfolio/-/blob/main/production/portfolio.yaml). But do we have to rethink our sources structure? what about  `levtype: hl`and `levtype: sol` and what about those cases where levtype is the same but some variables have different grid like:  

 ```yaml
  - levtype: o3d
    frequency: daily
    variables: [263500, 263501, 263505, 263506]
    resolutions: [standard, high]
    vertical: FESOM-full

  - levtype: o3d
    frequency: daily
    variables: [263507]
    resolutions: [standard, high]
    vertical: FESOM-half
```
Also, the info about the available resolutions should be extracted from [data-portfolio grids file](https://earth.bsc.es/gitlab/digital-twins/de_340-2/data-portfolio/-/blob/main/definitions/levels.yaml).
- the script takes the jinja template and substitutes the missing info taking it from the input config file (different for every exp). Levels and grids are taken from data-portfolio's files [here](https://earth.bsc.es/gitlab/digital-twins/de_340-2/data-portfolio/-/blob/main/definitions/levels.yaml) and [here](https://earth.bsc.es/gitlab/digital-twins/de_340-2/data-portfolio/-/blob/main/production/grids.yaml) (but the naming convention for the grids is different from ours).
- the info about the available resolutions should be extracted from the grids file.

what do you think? tagging everyone @oloapinivad @mnurisso @NataNazar @jhardenberg @ainagaya
