### ISSUE TITLE
New fixer for ifs-nemo reduced-plans in phase 2

### ISSUE THREAD

**Issue by mbatllem** [DestinE-Climate-DT/AQUA#1381]
### Discussion

Hello,

I've created a new fixer for the IFS-NEMO model, which I've been successfully using to analyze the IR experiments conducted using reduced plans and the `lab/kai/DE_CY48R1.0_climateDT_20240523_intel_gpp` model version. I believe it makes sense to include this as part of the existing `IFS-NEMO-climatedt-v2.yaml` configuration.

The fixer is as simple as:
```
  ifs-nemo-reduced-output-monthly-v2:
    parent: ifs-destine-v1
    data_model: ifs
    deltat: monthly
    vars:
      2t: 
        source: mean2t
        grib: true
      mtpr:
        source: tp
        grib: True
        # decumulate: true
        src_units: m
        units: kg m**-2 s**-1
```
