### ISSUE TITLE
unable to generate LRA

### ISSUE THREAD

**Issue by sebastianbeyer** [DestinE-Climate-DT/AQUA#1474]
### machine

MN5

### catalog

mn5-phase2

### version

main

### What happened?

There are two things, probably related. With the latest version of the catalog and [this](https://github.com/DestinE-Climate-DT/AQUA/pull/1462) PR in AQUA, I can do basic AQUA things, like 
```python
reader = Reader(model='IFS-FESOM', exp='a1ux', source='monthly-hpz7-atm2d', area=True, regrid='r025')
data = reader.retrieve()
datar = reader.regrid(data)
datar2 = data.aqua.regrid()
print(datar)
print(datar2)

reader = Reader(model='IFS-FESOM', exp='a1ux', source='daily-hpz7-oce2d', area=True, regrid='r025')
data = reader.retrieve()
datar = reader.regrid(data)
datar2 = data.aqua.regrid()
print(datar)
print(datar2)
```

I can also create the LRA with a config like this:

```yaml
# templates for LRA generation. Please modify everything between {{ }} according to your configuration

#This include the option for the regridding
target:
  resolution: r100
  frequency: monthly
  catalog: mn5-phase2

paths:
  outdir: /gpfs/scratch/ehpc01/sbeyer/test_lra_a1ux
  tmpdir: /gpfs/scratch/ehpc01/sbeyer/lra_temp

options:
  # loglevel
  loglevel: INFO
  # Set to True if lra-r100-monthly-zarr should be created and checked
  zarr: False
  verify_zarr: False

data:
  IFS-FESOM:
    a1ux:
      monthly-hpz7-atm2d:
        vars: ['mean2t']
           
        workers: 12  #this defines the workers for this source
      daily-hpz7-oce2d:
        vars: ['avg_sithick', 'avg_siconc', 'avg_sos', 'avg_tos', 'avg_zos']
        workers: 12 #this defines the workers for this source
      daily-hpz7-oce3d:
        workers: 6 #this defines the workers for this source
        vars: ['avg_thetao', 'avg_so']

```

So that's great!!
However I want the performance indices being plotted for my run so I need more variables in my LRA. I have no idea which ones are required, so I tried adding those from the data portfolio (reduced IFS-FESOM), but I have no idea how they need to be named (different eccodes versions, you know the problem)

When I now tried to use the eccodes version that I also used for running the model (2.35.1) in AQUA, (I hoped that I then could use the `grib_ls` built with the model to check my files for the variables names), I can not even do the first python code that I tested anymore.

### Code to reproduce the issue

```python
on MN5 remember to set 
`export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/gpfs/projects/ehpc01/sbeyer/models/DE_CY48R1.0_climateDT_tco399_fesom2.6/build/lib"` in order to use AQUA. 

otherwise, see the other box
```

### Error messages

..

### Are you interested in making a pull request?

Yes
