### ISSUE TITLE
variable name not changed by the fixer if not explicitely in the eccodes convention table

### ISSUE THREAD

**Issue by mnurisso** [DestinE-Climate-DT/AQUA#1566]
### machine

MN5

### catalog

mn5-phase2

### version

v0.13-alpha

### What happened?

If I retrieve the control-1990-freeze from mn5-phase2 ([here](https://github.com/DestinE-Climate-DT/Climate-DT-catalog/pull/102) the branch) I have sro (paramid 8) as surface runoff. Now, in our convention table we have:

```yaml
surfror: # Surface runoff rate
        source:
          - 8 # (m)
          - 235020 # avg_surfror
          - 231009 # surfror
          - 172008 # msror
          - avg_surfror
          - msror
          - surfror
          - mrros # cmor
```

If I don't explicitely also add -sro to the list of sources, the code understand that I have 8 matching, retrieves it but do not change the sro name to surfror. I can add sro to the list and the issue is solved, but do we want to understand if this should be solved also in the code somehow?

cc @jhardenberg @oloapinivad  

### Code to reproduce the issue

```python
from aqua import Reader
reader = Reader(model="IFS-NEMO", exp="control-1990-freeze", source="hourly-hpz9-atm2d", loglevel='DEBUG', fix=True)

# dataset will show sro and not surfror
```

### Are you interested in making a pull request?

Maybe
