### ISSUE TITLE
Fixing avg_tos and tprate for IFS-NEMO reduced output diagnostics

### ISSUE THREAD

**Issue by mbatllem** [DestinE-Climate-DT/AQUA#1598]
### Question

Hello, 
I'm generating the diagnostics for [a1z9](https://github.com/DestinE-Climate-DT/Climate-DT-catalog/blob/a1z9/catalogs/mn5-phase2/catalog/IFS-NEMO/a1z9.yaml) (I can do a PR if the outcome of this issue doesn't involve the catalog itself). This experiment used reduced output.

Apparently most of the diagnostics look good, besides the precipitation ones and the SST.

Regarding the precipitation, we have `tprate` variable, and the metadata looks like this (setting `fix=false` when reading it):
![Image](https://github.com/user-attachments/assets/199cc794-c2e2-4fef-8586-78a53765de42)
While generating the LRA, we are using the `ifs-nemo-reduced-output-monthly-v2` which has:
```
  ifs-nemo-reduced-output-monthly-v2:
    parent: ifs-destine-v1
    data_model: ifs
    deltat: monthly
    convention: eccodes
    vars:
      tprate:
        src_units: m
```

And the results: 

![Image](https://github.com/user-attachments/assets/a06be4f0-4055-4cca-b109-ba9817ee8bad)

Regarding the SST, the variable is `avg_tos` and the metada looks like this:

![Image](https://github.com/user-attachments/assets/75ed9f44-be61-4d56-901f-7f9c2c532328)

and the results:

![Image](https://github.com/user-attachments/assets/5379096b-04ec-481d-9113-539736667ee4)

Can we try to fix this? Any ideas?
