### ISSUE TITLE
Common configuration file template for diagnostics

### ISSUE THREAD

**Issue by silviacaprioli** [DestinE-Climate-DT/AQUA#1613]
### Feature request

Together with @oloapinivad and @mnurisso, we have prepared a preliminary template going in the direction of creating a unified configuration files for all diagnostics.

The structure includes:
- Common blocks shared across all diagnostics.
- Specific blocks tailored for individual diagnostics.

The draft text is provided below.

```yaml
datasets:
  - catalog: null # mandatory as null
    model: 'IFS-NEMO' # mandatory
    exp: 'historical-1990' # mandatory
    source: 'lra-r100-monthly' # mandatory
    regrid: null # if the diagnostic supports it
    freq: null # if the diagnostic supports it
  # Possible second/third/fourth datasets here, no present by default
  # - catalog: 'obs'
  #   model: 'ERA5'
  #   exp: 'era5'
  #   source: 'monthly'
  #   regrid: r100

# Block if the diagnostics needs a reference dataset
references:
  - catalog: 'obs' # mandatory
    model: 'ERA5' # mandatory
    exp: 'era5' # mandatory
    source: 'monthly' # mandatory
    regrid: null # if the diagnostic supports it
    freq: null # if the diagnostic supports it

setup:
  loglevel: 'WARNING'

output:
  outputdir: "./" # mandatory
  rebuild: true
  save_netcdf: true # mandatory if produced
  save_pdf: true # mandatory
  save_png: true # mandatory
  dpi: 300

diagnostic:
  teleconnections:
    NAO:
      run: true
      months_window: 3
      full_year: false
      seasons: ['DJF', 'JJA']
      cbar_range: [-5, 5]

  timeseries:
    run: true
    variables: ['2t', 'ie', 'msl',
                'tcc', 'lcc', 'mcc', 'hcc',
                'slhtf', #Mean surface latent heat flux
                'ishf', #Mean surface sensible heat flux
                'sdswrf', #Mean surface downward short-wave radiation flux
                'sdlwrf', #Mean surface downward long-wave radiation flux
                'snswrf', #Mean surface net short-wave radiation flux
                'snlwrf', #Mean surface net long-wave radiation flux
                'tnlwrf', #Mean top net long-wave radiation flux
                'tnswrf' #Mean top net short-wave radiation flux
                ]
    formulae: ['tnlwrf+tnswrf', '86400*tprate']
    plot_params:
      default:
        plot_ref: true
        monthly: true
        annual: true
        std_startdate: '1990-01-01'
        std_enddate: '2020-12-31'
        regions: null
      tnlwrf+tnswrf:
        longname: "Net top radiation"
      86400*tprate:
        longname: "Precipitation"
        regions: ['tropics', 'europe']

  gregory:
    run: true
    ts: '2t'
    toa: ['tnlwrf', 'tnswrf']
    monthly: true
    annual: true
  
  seasonal_cycles:
    run: true
    variables: ['2t', 'ie', 'msl',
                'tcc', 'lcc', 'mcc', 'hcc',
                'slhtf', #Mean surface latent heat flux
                'ishf', #Mean surface sensible heat flux
                'sdswrf', #Mean surface downward short-wave radiation flux
                'sdlwrf', #Mean surface downward long-wave radiation flux
                'snswrf', #Mean surface net short-wave radiation flux
                'snlwrf', #Mean surface net long-wave radiation flux
                'tnlwrf', #Mean top net long-wave radiation flux
                'tnswrf' #Mean top net short-wave radiation flux
                ]
    plot_params:
      default:
        plot_ref: true
        std_startdate: '1990-01-01'
        std_enddate: '2020-12-31'
        regions: null
  
  ecmean:
    run: true
    variables: ['2t', 'tprate', 'msl', 'ie', 'iews', 'inss', 'tcc', 'tsrwe',
                'tnswrf', 'tnlwrf', 'snswrf', 'snlwrf', 'ishf', 'slhtf',
                'u', 'v', 't', 'q', 'siconc', 'tos', 'sos']
    regions: ['Global', 'North Midlat', 'Tropical', 'South Midlat']
    seasons: ['ALL', 'DJF', 'JJA']
    year1: null # if you want to select some specific years, otherwise use the entire dataset
    year2: null
    # Goal is no config_file/interface exposed here
    setup:
      interface_file: 'interface_AQUA_climatedt.yaml'
      config_file: 'ecmean_config_climatedt.yaml'
  
  box_plot:
    run: true
    variables: ['-tnlwrf', 'tnswrf']

  # box_plot2 if another plot

  biases:
    run: true
    variables: ['tprate', '2t', 'msl', 'tnlwrf', 't', 'u', 'v', 'q', 'tos']
    plot_params:
      default:
        # Level plot for 2D bias map if variable 3d
        plev: [85000, 20000]
        seasons: true
        seasons_stat: 'mean' # May become a list
        # Vertical profile if variable 3d
        vertical: true
        # Default entire dataset
        startdate_data: null
        enddate_data: null
        startdate_ref: "1990-01-01"
        enddate_ref: "2020-12-31"
      2t:
        vmin: -15
        vmax: 15
      t:
        vmin: {85000: -20, 20000: -20, vertical: -20}
        vmax: {85000: 20, 20000: 20, vertical: 20}
  
  ocean_circulation:
    run: true
    ref: true # compare with reference dataset
    regions:
      Labrador Sea : DJF
      Irminger Sea : DJF
      Ross Sea : JJA
      Weddell Sea : JJA
      Gin Sea : DJF
    plots:
      [stratification, MLD]
  
  seaice_extent:
    run: true
    regions: ['Arctic', 'Southern Ocean']
    plot_params:
      vmin: 0 #placeholder
      vmax: 5
  
  tropical_rainfall:
    run: true
    trop_lat: [-15, 15]
    num_of_bins: 10000
    first_edge: 0
    width_of_bin: 0.5
    variables: ['tprate']
    startdate_ref: "1990-01-01"
    enddate_ref: "2020-12-31"
    auxiliary:
      imerg:
        default: null
        lumi: /path/to/lumi.nc
```
