### ISSUE TITLE
Integration of dynamical FDB HPC and DataBridge info coming from the Workflow in the

### ISSUE THREAD

**Issue by mnurisso** [DestinE-Climate-DT/AQUA#1617]
### Feature request

We sketch here what is the actual result of the internal discussion on how to be able to access updated info on which data have been transferred to the databridge and which have to be read from the HPC FDB.

## Yaml file produced by workflow

The first step is to have a yaml file with this structure

```yaml
# template for yaml info file
hpc:
    data_start_date: 19900101T0000 #experiment start (from workflow)
    data_end_date: 19990101T2300 #experiment current last timestep (from workflow)
    expver: a000 #experiment id
bridge:
    bridge_start_date: 19910101T0000 # could be null if no transfer has been done. first time step on the bridge
    bridge_end_date: 19920101T2300 # could be null if no transfer has been done. last time step on the bridge
    bridge_expver: o123 # could be null if no change has been done in the expver from hpc to bridge
```

possibly positioned in the `FDB_HOME` folder of the experiment. This should be written and updated by the workflow.

## Adaptation of the catalog generator

The catalog generator should be able to take a `FDB_HOME_DATABRIDGE` while the catalog source is generated.
If the workflow produces the yaml file generated above, this should be inserted instead of the string values with the dates that are inserted now by the catalog generator, meaning that the dynamical dates are turned on and that are now written in the catalog explicitely.

## Intake GSV update

Add to the intake gsv module the possibility to read a yaml file with the aspect described above and drop the reading from txt feature enabled atm, which is unused and deprecated.
