### ISSUE TITLE
Intake v2 migration issues investigation

### ISSUE THREAD

**Issue by mnurisso** [DestinE-Climate-DT/AQUA#1789]
We will use this issue to report on the possible issues in the update of intake package to v2.
In particular we need to check:

- [ ] integration of intake-xarray
- [ ] integration of intake-esm
- [ ] step needed for intake-gsv

**Comment by mnurisso** [comment]
The call:

`reader = Reader(model='NEMO', exp='test-eORCA1', source='long-2d')`

produces:

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[6], line 1
----> 1 reader = Reader('NEMO','test-eORCA1','long-2d')

File ~/AQUA/src/aqua/reader/reader.py:165, in Reader.__init__(self, model, exp, source, catalog, fix, regrid, regrid_method, areas, datamodel, streaming, stream_generator, startdate, enddate, rebuild, loglevel, nproc, aggregation, chunks, preproc, convention, **kwargs)
    163 # Manual safety check for netcdf sources (see #943), we output a more meaningful error message
    164 if isinstance(self.esmcat, intake_xarray.netcdf.NetCDFSource):
--> 165     if not files_exist(self.esmcat.urlpath):
    166         raise NoDataError(f"No NetCDF files available for {self.model} {self.exp} {self.source}, please check the urlpath: {self.esmcat.urlpath}") # noqa E501
    168 # store the kwargs for further usage

AttributeError: 'NetCDFSource' object has no attribute 'urlpath'
```

**Comment by mnurisso** [comment]
More deeply, if I open the catalog with pure intake:

`cat = intake.from_yaml_file('/Users/mnurisso/.aqua/catalogs/ci/catalog.yaml')`

I get:

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[16], line 1
----> 1 cat = intake.from_yaml_file('/Users/mnurisso/.aqua/catalogs/ci/catalog.yaml')

File /opt/homebrew/Caskroom/mambaforge/base/envs/aqua-intake2/lib/python3.12/site-packages/intake/readers/entry.py:433, in Catalog.from_yaml_file(path, **kwargs)
    431 of = fsspec.open(path, **storage_options)
    432 with of as stream:
--> 433     cat = Catalog.from_dict(yaml.safe_load(stream))
    434 cat.user_parameters["CATALOG_PATH"] = path
    435 cat.user_parameters["CATALOG_DIR"] = of.fs.unstrip_protocol(of.fs._parent(path))

File /opt/homebrew/Caskroom/mambaforge/base/envs/aqua-intake2/lib/python3.12/site-packages/intake/readers/entry.py:451, in Catalog.from_dict(cls, data)
    449 """Assemble catalog from dict representation"""
    450 if data.get("version") != 2:
--> 451     raise ValueError("Not a V2 catalog")
    452 cat = cls()
    453 for key, clss in zip(
    454     ["entries", "data", "user_parameters"],
    455     [ReaderDescription, DataDescription, BaseUserParameter],
    456 ):

ValueError: Not a V2 catalog
```

**Comment by mnurisso** [comment]
This first issue can be solved by adding:

`version: 2`

at the top of the main `catalog.yaml` file. However the issue is then:

```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[17], line 1
----> 1 cat = intake.from_yaml_file('/Users/mnurisso/.aqua/catalogs/ci/catalog.yaml')

File /opt/homebrew/Caskroom/mambaforge/base/envs/aqua-intake2/lib/python3.12/site-packages/intake/readers/entry.py:433, in Catalog.from_yaml_file(path, **kwargs)
    431 of = fsspec.open(path, **storage_options)
    432 with of as stream:
--> 433     cat = Catalog.from_dict(yaml.safe_load(stream))
    434 cat.user_parameters["CATALOG_PATH"] = path
    435 cat.user_parameters["CATALOG_DIR"] = of.fs.unstrip_protocol(of.fs._parent(path))

File /opt/homebrew/Caskroom/mambaforge/base/envs/aqua-intake2/lib/python3.12/site-packages/intake/readers/entry.py:457, in Catalog.from_dict(cls, data)
    452 cat = cls()
    453 for key, clss in zip(
    454     ["entries", "data", "user_parameters"],
    455     [ReaderDescription, DataDescription, BaseUserParameter],
    456 ):
--> 457     for k, v in data[key].items():
    458         if isinstance(v, dict):
    459             desc = clss.from_dict(v)

KeyError: 'entries'
```

**Comment by mnurisso** [comment]
The closest I got to a working netcdf entry is:

```yaml
version: 2  # Required for Intake v2
metadata: {}
user_parameters: {}  # This is required, even if it's empty
aliases: {'era5-hpz3': 'ERA5'}

data: # Not clear yet what it is
  ERA5:
    datatype: netcdf
    kwargs:
      url: './AQUA_tests/ERA5/hpz3/ERA5*.nc'
    metadata: {}
    user_parameters: {}

entries:
  xarray:
    kwargs: {}
    metadata: {}
    output_instance: xarray:Dataset
    reader: intake.readers.readers:XArrayDatasetReader
    user_parameters: {}
```

This can load the yaml, you can see `cat.data` and `cat.entries`, but cat.ERA5 (calling the alias, don't ask me what it is) gives me: `TypeError: 'module' object is not callable`.

If I call a method to create a catalog entry as yaml as shown [here](https://github.com/intake/intake/issues/805#issuecomment-2115408063) I get:

```yaml
aliases: {}
data:
  8e372d5df1e7708f:
    datatype: intake.readers.datatypes:HDF5
    kwargs:
      path: ''
      storage_options: null
      url: https://noaa-wod-pds.s3.amazonaws.com/2023/wod_pfl_2023.nc
    metadata: {}
    user_parameters: {}
entries:
  wod:
    kwargs:
      data: '{data(8e372d5df1e7708f)}'
    metadata: {}
    output_instance: xarray:Dataset
    reader: intake.readers.readers:XArrayDatasetReader
    user_parameters: {}
metadata: {}
user_parameters: {}
version: 2
```

which is what I tried to mimic above.

The documentation both for intake_xarray and intake is not helping, with no explicit example of catalog from yaml file provided. The only documentation available about it is `[here](https://intake.readthedocs.io/en/latest/catalog.html)`. This page is not listed in the main doc sidebar and is probably deprecated since most of the lines except one are older than v2.0.0.

I personally conclude that a more stable release of intake, with proper documentation is needed to think about doing drastic changes in our catalog. Like this I can see that many changes are needed but the documentation does not provide enough guidance in what should be really done and the meaning of all the dictionary required in the yaml files. I added them because of KeyErrors, not because I'm aware of what I am doing.

**Comment by oloapinivad** [comment]
I did some tests today, the old structure is still apparently doable and partially retrocompatible

```python
import intake

cat = intake.open_catalog("intake.yaml")
mycat = cat._entries['monthly']()
mycat.to_dask()
```

where `intake.yaml`

```yaml
plugins:
  source:
  - module: intake_xarray
sources:
  monthly:
    driver: netcdf
    description: "monthly output"
    metadata:
      source_grid_name: test-hpz3-nested
      fixer_name: ERA5-destine-v1
    args:
      urlpath: "/Users/paolo/Desktop/AQUA/AQUA_tests/models/ERA5/hpz3/ERA5*.nc"
```

However, the engine it fails complaining it is a not a netcdf file

**Comment by oloapinivad** [comment]
Ah! Apparently for netcdf the problem is only to specify the xarray engine. This works with intake 2.0.9 and intake-xarray 2.0.0

```yaml
sources:
  monthly:
    driver: netcdf
    description: "monthly output"
    metadata:
      source_grid_name: test-hpz3-nested
      fixer_name: ERA5-destine-v1
    args:
      urlpath: "/Users/paolo/Desktop/AQUA/AQUA_tests/models/ERA5/hpz3/ERA5*.nc"
      chunks:
        time: 1
      xarray_kwargs:
        engine: netcdf4
```

**Comment by oloapinivad** [comment]
If I then create a zarr entry like the following 

```yaml
  zarr:
    driver: zarr
    description: "zarr output"
    metadata:
      source_grid_name: test-hpz3-nested
      fixer_name: ERA5-destine-v1
    args:
      urlpath: "/Users/paolo/Desktop/AQUA/AQUA_tests/models/ERA5/ERA5.zarr"
      chunks:
        time: 1
```

it works out of the box with 

```python
cat = intake.open_catalog("intake.yaml")
cat.zarr.read()
```
