### ISSUE TITLE
Wrong match between data portfolio production and data resolution

### ISSUE THREAD

**Issue by youcheng-csc** [DestinE-Climate-DT/AQUA#1824]
### Question

Dear AQUA colleagues @mnurisso @silviacaprioli @ghosh97,

I am running only aqua (expid, a2bg) with the input from a simulation (a2aq). However, it echoes during the remote setup, 

```
raise KeyError(f'Wrong match between data portfolio {data_portfolio} and data resolution {self.resolution}')
KeyError: 'Wrong match between data portfolio production and data resolution '

``` 

More details at 
```
/gpfs/scratch/ehpc01/bsc655096/a2bg/LOG_a2bg
```

the setup for request is 

```
REQUEST:
      EXPVER: a2aq
      FDB_HOME: "/gpfs/scratch/ehpc01/experiments/a2aq/fdb"
      MODEL: "IFS-NEMO" ## I think?
      ACTIVITY: HighResMIP
      EXPERIMENT: cont
      DATA_PORTFOLIO: "production"
      VARS_HL: avg_thetao

```

Matteo @mnurisso has halped me to figure out that since half of the required keys are empty, the catalog generator will keep failing.

```
From the logs:

in config_catalog_REMOTE_SETUP:

repos:
  data-portfolio_path: "/gpfs/scratch/ehpc01/bsc655096/a2bg/git_project/data-portfolio"
  Climate-DT-catalog_path: "/gpfs/scratch/ehpc01/bsc655096/a2bg/git_project/catalog"
resolution: "" #Experiment resolution: production/develop/lowres (if production portfolio), intermediate (if reduced portfolio)
catalog_dir: "mn5-phase2" #the folder in Climate-DT-catalog where the catalog entry will be stored
# AQUA definitions
model: ""
exp: "0001"
fixer_name: "climatedt-phase2-production"
# Request/experiment definitions
activity: ""
experiment: ""
expver: "0001"
generation: ""
num_of_realizations: "1"
data_start_date: "19880101"
data_end_date: ""
bridge_end_date: ""
ocean_grid: ""
description: 'FDB IFS/NEMO historical run' # if commented out, it will be built by the script
# paths
fdb_home: "/gpfs/projects/ehpc01/dte/fdb"
fdb_home_bridge: ""
```
The question for me now is how to set up these missing keys? under request?
