### ISSUE TITLE
Implementation of 'pointers' in standard YAML definition for all diagnostics with CLI

### ISSUE THREAD

**Issue by tovaz92** [DestinE-Climate-DT/AQUA#1836]
### Discussion

1. Currently we are following the new structure from @mnurisso for all the config_files.yaml ([V0.13 Link](https://aqua.readthedocs.io/en/latest/diagnostics/guidelines/class_structure.html#command-line-interface-cli)):

```yaml
datasets:
    - catalog: null # mandatory as null
        model: 'IFS-NEMO' # mandatory
        exp: 'historical-1990' # mandatory
        source: 'lra-r100-monthly' # mandatory
        regrid: null # if the diagnostic supports it
        freq: null # if the diagnostic supports it

# Block if the diagnostics needs a reference dataset
references:
    - catalog: 'obs' # mandatory
        model: 'ERA5' # mandatory
        exp: 'era5' # mandatory
        source: 'monthly' # mandatory
        regrid: null # if the diagnostic supports it
        freq: null # if the diagnostic supports it

seaice_timeseries:
  run: true
  
...
```

&rarr; to better match the specific needs for individual diagnostics (e.g. for seaice CLI: having the information if a reference data file have as data domain only the Norther or Southern Hemisphere, although the coordinates are defined globally), and to avoid the operation of retrieving the data and check them to get such information, a solution is proposed in using the possibility of referencing and pointing internally to the .yaml files and to add separately more metadata.

This mean to use in the writing of the config_file something like:

```yaml
references:
  - &ref1
    catalog: 'obs'       # mandatory
    model: 'OSI-SAF'     # mandatory
    exp: 'osi-450'       # mandatory
    source: 'nh-monthly' # mandatory
    regrid: 'r100'

  - &ref2
    catalog: 'obs'       # mandatory
    model: 'OSI-SAF'     # mandatory
    exp: 'osi-450'       # mandatory
    source: 'sh-monthly' # mandatory
    regrid: 'r100' 

seaice_timeseries:
  run: true
  
...

  references:
    ref1:
      <<: *ref1
      domain: "nh"

    ref2:
      <<: *ref2
      domain: "sh"
```

Note that `&ref1`  is not written when the dict is produced but it is just used internally to avoid replication of metadata.

This solution would give a lot of flexibility to those who needs extra parameters for their CLI, but has the limitation of requiring care in avoiding mismatching when writing the file. 

2. Another point to discuss (independently from the above), is to add to the catalog metadata a 'domain': 'NH' or 'SH' (for instance) for the data, which carries information wether the file data can be found only in a specific region of the planet.
