### ISSUE TITLE
Centralize plotting limits and colorbar

### ISSUE THREAD

**Issue by oloapinivad** [DestinE-Climate-DT/AQUA#1853]
### Feature request

We are discussing possible ways to implement a centralised file/class to control the colors and limit values for each variable

A possible way forward is deduced in 3 steps

### level-0

Introduce a centralised file which defines. More details asap. What exceeds the limit will lead to saturation of colors with `extend='both'" activated. A configuration file might look like this below

```yaml
2t:
  units: K 
  abs: 
    central: 260
    delta: 10
    cbar: "RdBU_r"
 delta:
    delta: 10
    cbar: "RdBU_r"
```

### level-1

If vmin-vmax check find an overflow of colors, extend the color palette by increasing the number of delta. and potentially by centering the value. A new palette, slightly different, might be introduced to highlight plot differences

### level-2

Introduce a companion upper limit low level and upper level palette, that are activate only when vmin-vmax are achieved (or more concretely, that are always available and used only when necessary).
