### ISSUE TITLE
Refactor `aqua_analysis` to provide more flexible combination of diagnostics

### ISSUE THREAD

**Issue by oloapinivad** [DestinE-Climate-DT/AQUA#1910]
### Feature request

As per title, more asap

**Comment by mnurisso** [comment]
We need to clarify more what has to be done here so that @jhardenberg and me we can start working on the task

**Comment by jhardenberg** [comment]
what do you think? @mnurisso ?

**Comment by jhardenberg** [comment]
Ok, I gave it more thought, so here is a draft of how the config file could really look like. 

@mnurisso @oloapinivad @silviacaprioli 
Please check it and let me know if you agree and then I can proceed to implement it modifying aqua-analysis accordingly.
The groupings are loosely following what we will implement in the dashboard but, while I would align them as much as possible, I would keep the two concepts separate. The ultimate way how to group figures will still be determined by `config.grouping.yaml `(which we need to move to config / .aqua anyway). This is as close as we can probably get with the current diagnostics. The 'diagnostic_name' of each of them is still specified in the config file.

The main features are:

- an initial collection of cli tools (diagnostics) which can be used to compose the following 'metadiagnostics', under `cli:`

- a list of the actual diagnostics to run (also organized in metadiagnostic/diagnostic). These could be set to true/false or commented. There are several groups (group1, group2) and the idea is that a diagnostic in a group will be run only if all diagnostic in the previous grup have finished.

- The metadiagnostics like
```
atmosphere:
    timeseries:
       ....
   global_biases:
    ....
```
each of them with separate config files.
We still have the `nworkers` key but remember that (it is already like this now) it only specifies how many workers to use if a global dask server ("cluster") is not used and instead each diagnostic has its own separate server. The default is to use the global cluster. If `nworkers` is not specified it defaults to the value specified in the `job:` section .

Ok, here is a sample config file for aqua-analysis:

````
 # Configuration file for aqua-analysis.sh

# Variables $AQUA, $AQUA_CONFIG and $OUTPUT can be used to refer to the root directory of AQUA,
# the config directory (i.e. .aqua/diagnostics) and the output directory respectively

job:
    # The max_threads variable serves as a mechanism to control the maximum number of diagnostics being run concurrently
    # - If max_threads is set to 0 or a negative value: There is no limit on the number of parallel diagnostics,
    #                                                   and all processes run in parallel without waiting. 
    #                                                   This is suitable for situations where you want to utilize
    #                                                   the maximum available resources without any restrictions.
    # - If max_threads is set to a positive value: It limits the number of concurrent processes to the specified value. 
    #                                              After launching the designated number of diagnostics, the script waits
    #                                              for these to complete before launching additional ones. 
    #                                              This is useful when you are working on a system with limited
    #                                              resources, such as a login node

    max_threads: 0  # Set to the desired maximum number of threads, or leave it as 0 for no limit
    loglevel: "WARNING" # DEBUG, IN FO, WARNING, ERROR, CRITICAL
    nworkers: 8  # Default number of workers for each individial dask cluster, if not specified in each diagnostic
                 # This is is used only if no global cluster is used (using a global cluster is the default)
    
    # Run a check analysis to test the configuration and the presence of needed data
    # This also rebuild the area files, to avoid error with corrupted files
    run_checker: true
    
    # Default output directory for the analysis. Can be overridden by the command line arguments
    outputdir: "./output"

    # Default values, overriden from command line arguments
    catalog: null  # The catalog to use for the analysis
    model: "IFS-NEMO"
    exp: "historical-1990"
    source: "lra-r100-monthly"
    regrid: null

    script_path_base: "${AQUA}/src/aqua_diagnostics"  # Base directory for the diagnostic scripts
    config_path_base: "${AQUA_CONFIG}"  # Base directory for the config scripts

cluster:  # options for dask cluster (this works well on lumi)
    workers: 32
    threads: 1  # per worker
    memory_limit: 7GiB  # per worker

# List of available CLI tools (diagnostics)
cli:
  global_biases: "global_biases/cli_global_biases.py"
  timeseries: "timeseries/cli_timeseries.py"
  boxplots: "boxplots/cli_boxplots.py"
  teleconnections: "teleconnections/cli_teleconnections.py"
  ecmean: "ecmean/cli_ecmean.py"
  seaice: "seaice/cli_seaice.py"
  tropical_rainfall: "../../diagnostics/tropical_rainfall/cli/cli_tropical_rainfall.py"
  ocean3d_drift: "../../diagnostics/ocean3d/cli/cli_ocean3d.py"
  ocean3d_circulation: "../../diagnostics/ocean3d/cli/cli_ocean3d.py"

# Which of the diagnostics to run. Also if commented they will not be run
# The two groups are run one afte rthe other and more than two can be defined
run: 
  group1:
    climate_metrics:
      ecmean: true
    atmosphere:
      global_biases: true
      timeseries: true
    radiation:
      biases: true
      boxplots: true
    teleconnections:
      atmosphere: true
    water_cycle:
      tropical_rainfall: true
    ocean3d:
      drift: true
    seaice: true
  group2:  # add more diagnostics here to be run after the first group
    climate_metrics:
      gregory: true
    atmosphere:
      seasonal_cycles: true
    ocean2d:  
      timeseries: true
    radiation:
      timeseries: true
    teleconnections:
      ocean: true
    ocean3d:
      circulation: true


  # List of metadiagnostics and diagnostics

  # Each diagnostic tool (cli) can have the following options (all optional):
  #    nworkers: the number of workers to use for the diagnostic if a global dask cluster is not used. Default is 1.
  #              Notice: these are still provided mostly for testing the local cluster option,
  #              using a global cluster (not using this option) is the new default.
  #    config: the configuration file for the diagnostic.
  #    extra: extra command line arguments to pass to the diagnostic script.
  #    cli: identifies the cli script to use.
  #              Default script_path is "$script_path_base/$diagnostic/cli_${diagnostic}.py"
  #    nocluster: boolean, if set to true, the diagnostic will not use the global dask cluster. Default is false (needed for ECmean)
diagnostics:

  climate_metrics:
    ecmean:
      cli: ecmean
      nworkers: 4
      nocluster: true  # ECmean does not use the global dask cluster
      config: "ecmean/config_ecmean_cli.yaml"
    gregory:
      timeseries:
        cli: timeseries
        config: "radiation/cli/config_radiation-gregory.yaml" # this will become a config of the climate_metrics metadiag
  atmosphere:
    global_biases:
      nworkers: 16
      cli: global_biases
      config: "global_biases/cli/config_global_biases.yaml"
    timeseries:
      cli: timeseries
      config: "timeseries/config_timeseries_atm.yaml"
    seasonal_cycles:
      cli: timeseries
      config: "timeseries/config_seasonalcycles_atm.yaml"
  ocean2d:  
    timeseries:
      cli: timeseries
      config: "timeseries/config_timeseries_oce.yaml"
  radiation:
    biases:
      cli: global_biases
      config: "radiation/cli/config_radiation-biases.yaml"
    boxplots:
      cli: boxplots
      config: "radiation/cli/config_radiation-boxplots.yaml"
    timeseries:
      cli: timeseries
      config: "radiation/cli/config_radiation-timeseries.yaml"
  teleconnections:
    atmosphere:
      cli: teleconnections
      config: "teleconnections/config_teleconnections_atm.yaml"
    ocean:
      cli: teleconnections
      nworkers: 4
      config: "teleconnections/config_teleconnections_oce.yaml"
  water_cycle:
    tropical_rainfall:
      cli: tropical_rainfall
      nworkers: 16
      config: "tropical_rainfall/cli/cli_config_trop_rainfall.yml"
      extra: "--regrid=r100 --freq=M --xmax=75 --bufferdir=${OUTPUT}/tropical_rainfall/"
  ocean3d:
    drift:
      cli: ocean3d_drift
      config: "ocean3d/cli/config.drift.yaml"
    circulation:
      cli: ocean3d_circulation
      config: "ocean3d/cli/config.circulation.yaml"
  seaice:
    all:
      cli: seaice
      nworkers: 4
      config: "seaice/config_seaice.yaml"

````
