### ISSUE TITLE
No land-sea mask for ERA5 with regrid

### ISSUE THREAD

**Issue by mnurisso** [DestinE-Climate-DT/AQUA#263]
### machine

Levante

### What happened?

Land-sea mask is lost when regridding is applied on ERA5 data

Without regrid, for sst I obtain:

![output](https://github.com/oloapinivad/AQUA/assets/53175065/63a0bb7c-78b4-4146-b3d2-f7d1b92f003b)

with `regrid=r100`:

![output2](https://github.com/oloapinivad/AQUA/assets/53175065/1dd6a27b-6d6f-46e1-98e8-7a75d4c70ebc)

Notice that I have in my branch fixes for era5 from levante, specifically:

```yaml
monthly:
    data_model: False
        vars:
            msl:
                grib: true
                source: MSL
            sst:
                grib: true
                source: SSTK
                src_units: K
```

Secondary problem, values for sst appears to be multiplied by a factor  around 57, is it something wrong in my fixes?

### Code to reproduce the issue

```python
reader = Reader(model='ERA5',exp='era5',source='monthly',regrid='r100')
data = reader.retrieve(var='sst') # having fixes otherwise var='SSTK'
data = reader.regrid(data)
data.sst.isel(time=10).plot()
```

### Are you interested in making a pull request?

Maybe
