### ISSUE TITLE
Derived vars cannot be retrieved separately

### ISSUE THREAD

**Issue by oloapinivad** [DestinE-Climate-DT/AQUA#551]
### machine

Levante

### version

main

### What happened?

When retrieving a variable which is derived, probably under the 'default` category of the fixer, the code seems to be unable to get it. Unfortunately, I am not able to create a clean reproducible example, rather you need to define in the fixer something like this (this is how we realized this is occurring)

 ```
 CERES:
    ebaf-toa41:
        default:
            data_model: False
            vars:
                mtntrf: 
                    derived: 0.-toa_lw_all_mon
                    grib: true
                mtnsrf: 
                    derived: solar_mon-toa_sw_all_mon
                    grib: true
```

and then call the reader as below

### Code to reproduce the issue

```python
reader = Reader('CERES', 'ebaf-toa41', 'monthly', regrid='r100', loglevel='debug')
data = reader.retrieve(var='mtntrf')

KeyError: 'You are asking for variables which we cannot find in the catalog!'
```

### Are you interested in making a pull request?

Yes
