### ISSUE TITLE
Grids only as metadata (follow up of #520)

### ISSUE THREAD

**Issue by mnurisso** [DestinE-Climate-DT/AQUA#584]
PR #520 PR is neutral, it still allows both options (keeping actual structure or removing machine dependent grid files), so nothing will really change if it is merged yet (there would still be the work to move the grid info in all the catalogue metedata). 

@oloapinivad I like your suggestion to kill regrid.yaml completely. So, to understand, you suggest that we should have a section like this in config-aqua.yaml?
```

paths:
  levante:
    grids: /work/bb1153/b382075/aqua/grids
    weights: /work/bb1153/b382075/aqua/weights
    areas: /work/bb1153/b382075/aqua/areas

  lumi:
    paths:
      grids: /pfs/lustrep3/projappl/project_465000454/data/AQUA/grids
      weights: /pfs/lustrep3/projappl/project_465000454/data/AQUA/weights
      areas: /pfs/lustrep3/projappl/project_465000454/data/AQUA/areas
```

This leaves open the issue of where to specify the 'default' option for the various grids if they are not specified.....
Options are: 
1) give up completely default and always speciffy the grid in all catalogue entries  
2) assume a fixed default (in 90% of the cases it is lon-lat anyway) 
3) .... keep regrid.yaml only for this? 
4) .. alternatives?

_Originally posted by @jhardenberg in https://github.com/oloapinivad/AQUA/issues/520#issuecomment-1739306380_ (little context added by me)
