### ISSUE TITLE
Cannot interpolate HealPix NEMO grid in exp `a0ef`

### ISSUE THREAD

**Issue by oloapinivad** [DestinE-Climate-DT/AQUA#674]
### machine

Lumi

### version

main

### What happened?

While trying to provide support for HealPix data with NEMO experiments, we are facing a new problem when calling the regridder. The grid file is well specified and the output can be interpolated by CDO, but when we call the internal regridding method the interpolation fails, even if the land-sea mask is the right position.

<img width="640" alt="Schermata 2023-12-05 alle 14 55 02" src="https://github.com/DestinE-Climate-DT/AQUA/assets/28352235/5d1e694f-bf3c-4e3b-bad2-5123cc112d4d">

NEMO healpix grid is currently defined as:

```
  nemo-healpix:
    path:
      2d: $grids/HealPix/icon_hpx10_oce_2d.nc 
      level: $grids/HealPix/nemo_hpx10_oce_level.nc
    space_coord: ["ncells"]
    vert_coord: ["level"]
```

Grids are stored in  `/pfs/lustrep3/projappl/project_465000454/data/AQUA/grids/HealPix`

Calling `cdo remapcon,r360x180 nemo_hpx10_oce_2d.nc ~/scratch/prova.nc` works out as expected. 

Please use branch `fdb/a0ef_catalogue` to test

### Code to reproduce the issue

```python
from aqua import Reader
reader = Reader(model="NEMO", exp="coupled-spinup-1990-1991", source="monthly-1deg-2d", regrid='r100')
data = reader.retrieve()
reader.regrid(data['avg_tos'][1,:]).plot()
```

### Are you interested in making a pull request?

Yes
