### ISSUE TITLE
OPA time conflicts with data model

### ISSUE THREAD

**Issue by oloapinivad** [DestinE-Climate-DT/AQUA#881]
### machine

Others

### version

main

### What happened?

The OPA entry generated in the workflow is using the fixes (`fixer_name`) to standardize the ouput of the LRA, and it should look like this below:

```
  opa:
      driver: netcdf
      args:
          urlpath: /scratch/project_465000454/caprioli/a0jo/tmp/*.nc
          chunks: {}
          xarray_kwargs:
            decode_times: True
      metadata:
        source_grid_name: 'lon-lat'
        fixer_name: ifs-destine-v1
```

However, now the OPA output files has `forecast_reference_time` as a standard name of the time coordinate (tagging @kat-grayson for information), so that when we open the resulting file the with the fixes on we get this weird structure. 

<img width="779" alt="Schermata 2024-02-14 alle 08 07 03" src="https://github.com/DestinE-Climate-DT/AQUA/assets/28352235/ac142e5c-27a2-489a-b989-a12d722baa0a">

This does not happen if we do not use the fixer since probably something is done by the datamodel to the time axis. It is probable that the data model assign the standard name to the coordinates. 

Of course, nothing works since now the time axis is no longer compatible with AQUA which expects a `time` coordinates. 

### Code to reproduce the issue

```python
from aqua import Reader
reader = Reader('IFS-NEMO', 'historical-1990', 'opa', fix=False)
test = reader.retrieve()
reader.timmean(test['2t'],freq="yearly", exclude_incomplete=True)
```

### Are you interested in making a pull request?

None
